// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgIds.proto

package com.chatsystem.msg;

public final class MsgIds {
  private MsgIds() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum MSG_ID
      implements com.google.protobuf.ProtocolMessageEnum {
    M_SignUp(0, 1),
    M_Login(1, 2),
    M_Auth(2, 3),
    M_UserInit(3, 4),
    M_GetAllUsers(4, 5),
    M_Chat(5, 6),
    M_AddRelation(6, 7),
    M_DelRelation(7, 8),
    M_AddRelationGroup(8, 9),
    M_MoveRelation(9, 10),
    M_FindUser(10, 11),
    M_NotifyLogin(11, 12),
    M_NotifyLogoff(12, 13),
    M_CreateChatRoom(13, 14),
    M_JoinChatRoom(14, 15),
    M_GetAllChatRoom(15, 16),
    M_ChatRoomNotify(16, 17),
    M_LeaveChatRoom(17, 18),
    M_EasyLogin(18, 19),
    M_ErrorCode(19, 100),
    ;
    
    public static final int M_SignUp_VALUE = 1;
    public static final int M_Login_VALUE = 2;
    public static final int M_Auth_VALUE = 3;
    public static final int M_UserInit_VALUE = 4;
    public static final int M_GetAllUsers_VALUE = 5;
    public static final int M_Chat_VALUE = 6;
    public static final int M_AddRelation_VALUE = 7;
    public static final int M_DelRelation_VALUE = 8;
    public static final int M_AddRelationGroup_VALUE = 9;
    public static final int M_MoveRelation_VALUE = 10;
    public static final int M_FindUser_VALUE = 11;
    public static final int M_NotifyLogin_VALUE = 12;
    public static final int M_NotifyLogoff_VALUE = 13;
    public static final int M_CreateChatRoom_VALUE = 14;
    public static final int M_JoinChatRoom_VALUE = 15;
    public static final int M_GetAllChatRoom_VALUE = 16;
    public static final int M_ChatRoomNotify_VALUE = 17;
    public static final int M_LeaveChatRoom_VALUE = 18;
    public static final int M_EasyLogin_VALUE = 19;
    public static final int M_ErrorCode_VALUE = 100;
    
    
    public final int getNumber() { return value; }
    
    public static MSG_ID valueOf(int value) {
      switch (value) {
        case 1: return M_SignUp;
        case 2: return M_Login;
        case 3: return M_Auth;
        case 4: return M_UserInit;
        case 5: return M_GetAllUsers;
        case 6: return M_Chat;
        case 7: return M_AddRelation;
        case 8: return M_DelRelation;
        case 9: return M_AddRelationGroup;
        case 10: return M_MoveRelation;
        case 11: return M_FindUser;
        case 12: return M_NotifyLogin;
        case 13: return M_NotifyLogoff;
        case 14: return M_CreateChatRoom;
        case 15: return M_JoinChatRoom;
        case 16: return M_GetAllChatRoom;
        case 17: return M_ChatRoomNotify;
        case 18: return M_LeaveChatRoom;
        case 19: return M_EasyLogin;
        case 100: return M_ErrorCode;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<MSG_ID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MSG_ID>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MSG_ID>() {
            public MSG_ID findValueByNumber(int number) {
              return MSG_ID.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.chatsystem.msg.MsgIds.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final MSG_ID[] VALUES = {
      M_SignUp, M_Login, M_Auth, M_UserInit, M_GetAllUsers, M_Chat, M_AddRelation, M_DelRelation, M_AddRelationGroup, M_MoveRelation, M_FindUser, M_NotifyLogin, M_NotifyLogoff, M_CreateChatRoom, M_JoinChatRoom, M_GetAllChatRoom, M_ChatRoomNotify, M_LeaveChatRoom, M_EasyLogin, M_ErrorCode, 
    };
    
    public static MSG_ID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private MSG_ID(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.chatsystem.msg.MSG_ID)
  }
  
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014MsgIds.proto\022\022com.chatsystem.msg*\364\002\n\006M" +
      "SG_ID\022\014\n\010M_SignUp\020\001\022\013\n\007M_Login\020\002\022\n\n\006M_Au" +
      "th\020\003\022\016\n\nM_UserInit\020\004\022\021\n\rM_GetAllUsers\020\005\022" +
      "\n\n\006M_Chat\020\006\022\021\n\rM_AddRelation\020\007\022\021\n\rM_DelR" +
      "elation\020\010\022\026\n\022M_AddRelationGroup\020\t\022\022\n\016M_M" +
      "oveRelation\020\n\022\016\n\nM_FindUser\020\013\022\021\n\rM_Notif" +
      "yLogin\020\014\022\022\n\016M_NotifyLogoff\020\r\022\024\n\020M_Create" +
      "ChatRoom\020\016\022\022\n\016M_JoinChatRoom\020\017\022\024\n\020M_GetA" +
      "llChatRoom\020\020\022\024\n\020M_ChatRoomNotify\020\021\022\023\n\017M_" +
      "LeaveChatRoom\020\022\022\017\n\013M_EasyLogin\020\023\022\017\n\013M_Er",
      "rorCode\020d"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
